# Base joystick parameters for OSR
teleop_twist_joy:
  ros__parameters:
    axis_linear.x: 3        # which joystick axis to use for driving
    axis_angular.yaw: 2     # which joystick axis to use for turning
    axis_angular.pitch: 0   # which joystick axis to use for in-place rotation
    scale_linear.x: -0.4          # scale to apply to drive speed, in m/s: drive_motor_rpm * 2pi / 60 * wheel radius * slowdown_factor
    scale_angular.yaw: -1.25      # scale to apply to angular speed, in rad/s: scale_linear / min_radius(=0.45m)
    scale_angular.pitch: 0.25     # scale to apply to angular speed, in rad/s: scale_linear / min_radius(=0.45m)
    scale_linear_turbo.x: 1.78    # scale to apply to linear speed, in m/s
    scale_angular_turbo.yaw: 3.95 # scale to apply to angular speed, in rad/s: scale_linear_turbo / min_radius
    enable_button: 0          # which button to press to enable movement
    enable_turbo_button: -1   # -1 to disable turbo